### PR TITLE
add genius.com

### PR DESCRIPTION
**Pull request by rsify**

### CODE REVIEW

**Comment by nikivdev** [comment]
Thank you.

**Comment by nikivdev** [comment]
This will be available in a bit in the workflow.

I want to improve the workflow so it fetches things from GitHub and caches it and not bundle the queries with the workflow.

Will try do that soon.

**Comment by rsify** [comment]
Can't wait! :)

**Comment by rsify** [comment]
Perhaps you could move the csv file to a different repo for simplicity, and just keep this one for workflow issues/features?

**Comment by nikivdev** [comment]
I was thinking of putting `websites.csv` at root of the repo. Then have Alfred ping GitHub for updates occasionally, get the websites.csv and save that to Alfred dir.

Also with that I want to add support for user's custom queries that they don't want to add globally to the workflow. So both user & global queries will be available for searching.

**Comment by rsify** [comment]
I was just saying to unclutter the main repo's commit history from one-two line "add website" commits and instead move that to somewhere else. Love the idea with custom queries though!

**Pull request merged**
